-- Use role and warehouse
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

-- Create database
CREATE OR REPLACE DATABASE ESG_PL_DB;

-- Create schemas
CREATE OR REPLACE SCHEMA ESG_PL_DB.ESG_RAW;
CREATE OR REPLACE SCHEMA ESG_PL_DB.ESG_SILVER;
CREATE OR REPLACE SCHEMA ESG_PL_DB.ESG_GOLD;